services:
  oracle:
    image: container-registry.oracle.com/database/express
    container_name: oracle-xe
    restart: unless-stopped
    ports:
      - "1521:1521"   # Oracle Listener
      - "5500:5500"   # Enterprise Manager Express
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata  # Persistent database storage

volumes:
  oracle_data: