version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    environment:
      - TZ=Europe/Sofia
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data